import React, { useState } from 'react';
import { generateAiSolution } from '../services/geminiService';
import { Bot, Send, Loader2, Sparkles, AlertCircle } from 'lucide-react';
import { Solution, Category } from '../types';

interface AIFixerProps {
  onSolutionGenerated: (solution: Solution) => void;
}

const AIFixer: React.FC<AIFixerProps> = ({ onSolutionGenerated }) => {
  const [prompt, setPrompt] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!prompt.trim()) return;

    setLoading(true);
    setError(null);

    try {
      const resultText = await generateAiSolution(prompt);
      
      // Create a temporary "solution" object from the AI response
      const aiSolution: Solution = {
        id: Math.floor(Math.random() * 10000) + 1000, // Random ID for transient AI solutions
        title: `AI Fix: ${prompt.slice(0, 30)}${prompt.length > 30 ? '...' : ''}`,
        category: Category.AI,
        shortDescription: "Generated by Gemini AI specifically for your query.",
        fullContent: resultText,
        tags: ["AI", "Generated", "Custom"],
        likes: 0
      };

      onSolutionGenerated(aiSolution);
      setPrompt('');
    } catch (err) {
      setError("Failed to generate solution. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="max-w-4xl mx-auto mb-12 animate-in slide-in-from-bottom-4 duration-500">
      <div className="bg-gradient-to-br from-indigo-900/50 to-slate-900/50 border border-indigo-500/30 rounded-2xl p-1 shadow-2xl shadow-indigo-500/10">
        <div className="bg-slate-900 rounded-xl p-6 sm:p-8">
          
          <div className="flex items-center gap-3 mb-6">
            <div className="bg-indigo-500/20 p-2 rounded-lg">
                <Sparkles className="w-6 h-6 text-indigo-400" />
            </div>
            <div>
                <h2 className="text-xl font-bold text-white">Can't find a fix? Ask AI.</h2>
                <p className="text-slate-400 text-sm">Powered by Gemini 3 Flash</p>
            </div>
          </div>

          <form onSubmit={handleSubmit} className="relative">
            <div className="relative">
                <Bot className="absolute top-3.5 left-4 w-5 h-5 text-indigo-400" />
                <textarea
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                placeholder="Describe your problem... (e.g., 'How do I remove a stripped screw?', 'My python script is slow')"
                className="w-full bg-slate-800/50 border border-slate-700 rounded-xl py-3 pl-12 pr-32 text-slate-200 placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent min-h-[60px] resize-none transition-all"
                rows={2}
                onKeyDown={(e) => {
                    if (e.key === 'Enter' && !e.shiftKey) {
                        e.preventDefault();
                        handleSubmit(e);
                    }
                }}
                />
                <div className="absolute bottom-2.5 right-2.5">
                    <button
                        type="submit"
                        disabled={loading || !prompt.trim()}
                        className={`flex items-center gap-2 px-4 py-1.5 rounded-lg text-sm font-semibold transition-all ${
                        loading || !prompt.trim()
                            ? 'bg-slate-700 text-slate-500 cursor-not-allowed'
                            : 'bg-indigo-600 hover:bg-indigo-500 text-white shadow-lg shadow-indigo-500/25'
                        }`}
                    >
                        {loading ? (
                        <>
                            <Loader2 className="w-4 h-4 animate-spin" />
                            Thinking...
                        </>
                        ) : (
                        <>
                            Fix It <Send className="w-3 h-3" />
                        </>
                        )}
                    </button>
                </div>
            </div>
            {error && (
                <div className="absolute -bottom-8 left-0 flex items-center gap-2 text-rose-400 text-xs animate-in fade-in">
                    <AlertCircle className="w-3 h-3" /> {error}
                </div>
            )}
          </form>

        </div>
      </div>
    </div>
  );
};

export default AIFixer;
